#!/bin/bash

# default variables
# better location to save data
zadir=~/.local/share/zaread/
reader="zathura"


# if ~/.zaread doesn't exist, we create it.
if [[ ! -d "$zadir" ]]; then
	mkdir -p "$zadir"cksum
fi

# if no arguments exit.
if [[ -z $1 ]]; then exit 1; fi

# this enables zaread to open multiple files at once
for i in "$@"; do

	# basename exists for a reason
	file=$(basename "$i")

	# if file type is pdf, then just read the file
	if [[ $(file --mime-type "$file" | awk -F':' '{print $2}') =~ pdf$  ]]; then
		echo "The file is already in PDF format."
		$reader --fork "$file"
		# else check if you already have its pdf version (if not, create it)
	else
		pdffile=${file%.*}".pdf"
		check=$(cksum "$file" | awk '{print $1}')
		# if pdf version hasn't ever been created, or it changed, then
		# make conversion and store the checksum.
		if [[ ( ! -f "$zadir$pdffile" ) || ( ! "$check" == $(cat "$zadir"cksum/"$file".check) ) ]]; then
			# if it's a mobi file, then convert it to epub (the command depends on calibre)
			if [[ "$file" =~ ^.*\.mobi$ ]]; then
				ebook-converter "$file" $(echo "$file" | sed 's/mobi$/epub/')
			else
				libreoffice --convert-to pdf "$file" --headless --outdir "$zadir"
			fi

			echo "$check" > "$zadir"cksum/"$file".check
		fi
		$reader --fork "$zadir$pdffile"
	fi
done

